### ISSUE TITLE
Feature: Populate docs

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-chart#8]
Needs to be done prior to official release

### TODO
* [ ] ensure readme docs are sufficient
* [ ] generate `Chart` component prop docs
* [ ] write drawing architecture docs
* [ ] write basic examples for each piece of `Chart` wrapper management
  * [ ] handling resize
  * [ ] updating & persisting indicators
  * [ ] updating & persisting drawings
  * [ ] updating data
  * [ ] updating orders
  * [ ] updating trades
  * [ ] updating positions
